# Generated by Django 3.0.6 on 2020-05-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcpbe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='fb_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
